/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/signals` | `/signals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/defi` | `/defi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat/[agentId]` | `/chat/[agentId]`, params: Router.UnknownInputParams & { agentId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/signals` | `/signals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/rewards` | `/rewards`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/defi` | `/defi`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chat/[agentId]` | `/chat/[agentId]`, params: Router.UnknownOutputParams & { agentId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/signals${`?${string}` | `#${string}` | ''}` | `/signals${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/rewards${`?${string}` | `#${string}` | ''}` | `/rewards${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/defi${`?${string}` | `#${string}` | ''}` | `/defi${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/signals` | `/signals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/defi` | `/defi`; params?: Router.UnknownInputParams; } | `${'/(app)'}/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/chat/[agentId]` | `/chat/[agentId]`, params: Router.UnknownInputParams & { agentId: string | number; } };
    }
  }
}
